# Generated by Django 3.0.6 on 2020-06-29 09:35

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Tweet_users',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.CharField(max_length=128, unique=True)),
                ('screen_name', models.CharField(max_length=129)),
                ('name', models.CharField(max_length=128)),
                ('profile_image_url', models.CharField(max_length=128)),
                ('followers', models.CharField(max_length=128)),
            ],
        ),
    ]
