# Generated by Django 3.0.6 on 2020-06-29 12:40

import django.contrib.postgres.fields.jsonb
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('tweeteranalysis', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tweettimeline',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(max_length=128)),
                ('created_date', models.DateField(blank=True, default=django.utils.timezone.now)),
                ('url', models.CharField(max_length=300)),
                ('media_data', models.CharField(max_length=300)),
                ('user_details', django.contrib.postgres.fields.jsonb.JSONField(blank=True, default=dict)),
                ('retweet_count', models.IntegerField(default=0)),
                ('favourite_count', models.IntegerField(default=0)),
                ('hashtag', django.contrib.postgres.fields.jsonb.JSONField(blank=True, default=dict)),
                ('tweetid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tweeteranalysis.Tweet_users')),
            ],
        ),
    ]
