# Generated by Django 3.0.6 on 2020-06-29 16:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tweeteranalysis', '0002_tweettimeline'),
    ]

    operations = [
        migrations.AddField(
            model_name='tweettimeline',
            name='uniqueid',
            field=models.CharField(blank=True, max_length=128),
        ),
    ]
