# Generated by Django 3.0.6 on 2020-06-29 16:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tweeteranalysis', '0003_tweettimeline_uniqueid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tweettimeline',
            name='text',
            field=models.CharField(max_length=500),
        ),
    ]
