# Generated by Django 3.0.6 on 2020-05-14 11:54

import datetime
from django.conf import settings
import django.contrib.postgres.fields.jsonb
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('pages', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Addetails',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('adid', models.CharField(max_length=128)),
                ('start_date', models.CharField(blank=True, max_length=128)),
                ('end_date', models.CharField(blank=True, max_length=128)),
                ('searched_date', models.DateField(default=datetime.date(2020, 5, 14))),
                ('ad_info', django.contrib.postgres.fields.jsonb.JSONField()),
                ('productid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pages.Pagesdetail')),
                ('userid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
