# Generated by Django 3.0.6 on 2020-05-18 04:34

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0002_addetails'),
    ]

    operations = [
        migrations.AlterField(
            model_name='addetails',
            name='searched_date',
            field=models.DateField(default=datetime.date(2020, 5, 18)),
        ),
        migrations.AlterField(
            model_name='pagesdetail',
            name='page_id',
            field=models.CharField(max_length=128, unique=True),
        ),
    ]
