# Generated by Django 3.0.6 on 2020-05-20 06:06

import django.contrib.postgres.fields.jsonb
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0004_auto_20200520_1150'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pagesdetail',
            name='facebook_tracker',
            field=django.contrib.postgres.fields.jsonb.JSONField(blank=True, default=dict),
        ),
        migrations.AlterField(
            model_name='pagesdetail',
            name='insatgram_tracker',
            field=django.contrib.postgres.fields.jsonb.JSONField(blank=True, default=dict),
        ),
    ]
