# Generated by Django 3.0.6 on 2020-05-23 11:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0006_auto_20200523_0956'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='expiredads',
            name='adid',
        ),
        migrations.RemoveField(
            model_name='expiredads',
            name='created_time',
        ),
        migrations.RemoveField(
            model_name='expiredads',
            name='start_date',
        ),
    ]
