# Generated by Django 3.0.6 on 2020-05-27 08:56

import datetime
from django.db import migrations, models
import django.db.models.deletion
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0007_auto_20200523_1658'),
    ]

    operations = [
        migrations.CreateModel(
            name='Socialmedia_tracker',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fb_likes', models.CharField(max_length=128)),
                ('insta_likes', models.CharField(max_length=128)),
                ('date', models.DateField(default=datetime.datetime(2020, 5, 27, 8, 56, 1, 909887, tzinfo=utc))),
                ('productid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pages.Pagesdetail')),
            ],
        ),
    ]
