# Generated by Django 3.0.6 on 2020-05-27 09:12

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0008_socialmedia_tracker'),
    ]

    operations = [
        migrations.AddField(
            model_name='socialmedia_tracker',
            name='fb_stats',
            field=models.CharField(blank=True, max_length=128),
        ),
        migrations.AddField(
            model_name='socialmedia_tracker',
            name='insta_stats',
            field=models.CharField(blank=True, max_length=128),
        ),
        migrations.AlterField(
            model_name='socialmedia_tracker',
            name='date',
            field=models.DateField(default=datetime.datetime(2020, 5, 27, 9, 12, 41, 533285, tzinfo=utc)),
        ),
    ]
