# Generated by Django 3.0.6 on 2020-05-27 09:13

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0009_auto_20200527_1457'),
    ]

    operations = [
        migrations.AlterField(
            model_name='socialmedia_tracker',
            name='date',
            field=models.DateField(default=django.utils.timezone.now),
        ),
    ]
