# Generated by Django 3.0.6 on 2020-05-30 04:31

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0010_auto_20200527_1458'),
    ]

    operations = [
        migrations.AddField(
            model_name='pagesdetail',
            name='searched_date',
            field=models.DateField(blank=True, default=django.utils.timezone.now),
        ),
    ]
