# Generated by Django 3.0.6 on 2020-05-31 03:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0011_pagesdetail_searched_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='pagesdetail',
            name='total_ads',
            field=models.CharField(blank=True, max_length=128),
        ),
    ]
