# Generated by Django 3.0.6 on 2020-06-03 05:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0012_pagesdetail_total_ads'),
    ]

    operations = [
        migrations.CreateModel(
            name='Adstracker',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.CharField(max_length=128)),
                ('month', models.CharField(max_length=128)),
                ('date', models.CharField(max_length=128)),
                ('weekday', models.CharField(max_length=128)),
                ('adid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pages.Addetails')),
            ],
        ),
    ]
