# Generated by Django 3.0.6 on 2020-06-14 16:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0013_adstracker'),
    ]

    operations = [
        migrations.AddField(
            model_name='addetails',
            name='mul_type',
            field=models.CharField(blank=True, max_length=128),
        ),
    ]
