# Generated by Django 3.0.6 on 2020-06-14 17:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0014_addetails_mul_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='addetails',
            name='mul_type_link',
            field=models.CharField(blank=True, max_length=128),
        ),
    ]
