# Generated by Django 3.0.6 on 2020-06-15 06:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0015_addetails_mul_type_link'),
    ]

    operations = [
        migrations.AlterField(
            model_name='addetails',
            name='mul_type_link',
            field=models.CharField(blank=True, max_length=5000),
        ),
    ]
