# Generated by Django 3.0.6 on 2020-05-18 04:34

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users_details', '0002_auto_20200514_1412'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usersearchhistory',
            name='date',
            field=models.DateField(default=datetime.date(2020, 5, 18)),
        ),
    ]
