# Generated by Django 3.0.6 on 2020-05-20 06:05

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('users_details', '0003_auto_20200518_1019'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usersearchhistory',
            name='date',
            field=models.DateField(default=django.utils.timezone.now),
        ),
    ]
