# Generated by Django 3.0.6 on 2020-05-27 10:19

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('pages', '0010_auto_20200527_1458'),
        ('users_details', '0004_auto_20200520_1150'),
    ]

    operations = [
        migrations.CreateModel(
            name='Userpages',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(verbose_name=django.utils.timezone.now)),
                ('productid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pages.Pagesdetail')),
                ('userid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
